name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    FRONTIFY_INSTANCE_DOMAIN: 'frontify.alev.cloud'

jobs:
    run-action:
        name: Run action
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm i --frozen-lockfile

            - name: Check formatting of code
              run: pnpm format

            - name: Bundle the code
              run: pnpm build

            - name: Package for GitHub Actions
              run: pnpm package

            - name: Run deployment action (single app)
              uses: ./
              with:
                  path: ./tests/dummy-block
                  instanceDomain: ${{ env.FRONTIFY_INSTANCE_DOMAIN }}
                  token: ${{ secrets.FRONTIFY_TOKEN }}

            - name: Run deployment action (monorepo with multiple apps)
              uses: ./
              with:
                  path: ./tests/dummy-blocks-monorepo/*
                  instanceDomain: ${{ env.FRONTIFY_INSTANCE_DOMAIN }}
                  token: ${{ secrets.FRONTIFY_TOKEN }}
